### ISSUE TITLE
Spanish Language Pack

### ISSUE THREAD

**Issue by IamDarkle** [rob006-software/flarum-translations#487]
Hello! we are currently working on a new Spanish language pack (https://github.com/FlarumES/lang-spanish) for Flarum made by the verified community FlarumES.com. 

I would like to add the repo but first I would like to say that we are working on different branches that can be selected from the extension, initially for Formal and Informal Spanish but in the future for other Spanish dialects (Mexican, Argentinian, Chilean...) is it possible to manage these branches from Weblate?

**Comment by rob006** [comment]
Weblate supports [multiple dialects for Spanish](https://github.com/WeblateOrg/language-data/blob/14985a50a2bfa4cc824d2db95197880254003c4c/languages.csv#L153-L170) but I don't see separation for formal and informal (although Weblate allows to add custom languages, so we could just add "Spanish (formal)"). So there should be no problem with handling multiple dialects in Weblate, but I'm not sure if it will be optimal for you. 

In Weblate each dialect will be treated as separate language, so if you have 5 dialects, you will need to translate each string 5 times, even if result is always the same, since Weblate will not automatically propagate translations from "Spanish" to "Spanish (Argentina)". If differences will be mostly cosmetic, it may be more efficient to add one language to Weblate as basic Spanish, export translations to one repository (Spanish language pack), and then fork this repo and change only necessary parts by editing  YAML files directly in fork (to adjust translations for Argentinian dialect). While it may be less convenient to translate, you will be able to inherit all new translations by just merging changes from upstream - much less work if most of translations will be the same.

**Comment by IamDarkle** [comment]
These are very interesting points, perhaps as you say, for our needs it is not the most optimal, at least at the beginning (still having to do so many translations). For now we are going to work on the new extension to have a solid base and add the first dialects, some of them are very different and will require more work so we will have to look at that.

Thank you very much for your time, if you prefer you can close the issue for now.

**Comment by rob006** [comment]
So you don't want to add Spanish to Weblate? If you want to work on single dialect, there should be no problems and it may simplify many things.

If you're interested, here are instructions how to start: https://github.com/rob006-software/flarum-translations/wiki/How-to-start

**Comment by IamDarkle** [comment]
Hi! sorry for the delay, I was busy with some things, yesterday was the PR of the final structure of the extension we are developing, so the final structure is as follows:

- en-ES-formal
- en-ES-informal

With the future dialects new folders will be added, so it will look like this:

- en-ES-formal
- en-ES-informal
- es-MX-formal
- es-AR-formal

I have thought about it and according to what you told me the option of adding the languages separately is not such a bad idea, currently we will only have es-ES-formal and es-ES-informal, both will be updated synchronously and actively, in the case of dialects will depend on the entry of new contributors who are interested in making new dialects, so it would be a good idea what you said that in the case of dialects work directly from the [repo](https://github.com/FlarumES/lang-spanish/tree/main/locale)

In this way in Weblate we would have Formal Spanish and Informal Spanish, if this sounds good to you, we can start adding Spanish to Weblate 😃

**Comment by rob006** [comment]
Honestly, it looks really overcomplicated to me. Wouldn't be easier to keep every dialect in separate repo as separate extension? In that  case you could actually have both "Spanish" to "Spanish (Argentina)" active at the same time and allow switch between them. It would also make these extensions lighter - if you're interested only in one dialect, you would not need to download and keep files for all of them, since you would install only extension you need. 

I could add "Spanish" and "Spanish (formal)" now, but I really feel like you are bringing yourself more work this way. :) I just quickly compared both variants in https://github.com/FlarumES/lang-spanish/pull/2 and it looks like 95% translations are the same. With one "Spanish" on Weblate and "Spanish (formal)" handled as fork with separate extension, you would skip copying and pasting 95% content. While it make sense to add separate dialects for Argentina or Mexico, since there may be more differences there, I don't think it is worth to do this for formal/informal, since this is basically the same language.

**Comment by IamDarkle** [comment]
The idea was that by centralising the development in a single extension it would be easier to develop and maintain, avoiding having a lot of extensions and repositories to maintain, which share the same language but with different dialects/registers (formal and informal). I also believe that it will be easier for users to install and maintain a single package. 

We consider that a dialect or registry is an administrator preference, in the case of dialects an even more specific localization of the forum, so I don't really think an administrator would be interested in having multiple active Spanish dialects in his forum, with that in mind we came up with the idea that from the frontend of the extension you could select the preference. 

![](https://media.discordapp.net/attachments/816429050561298472/823321533724360704/unknown.png)

Actually there would be no problem to add only the Formal Spanish, simply called "Spanish" in Weblate, really the main point is the convenience of having the .yml files updated and easy to translate from the Weblate platform. Then for our part it would be as simple as cloning this file and make the necessary small modifications from the repo for the other registers or dialects.

**Comment by rob006** [comment]
> Then for our part it would be as simple as cloning this file and make the necessary small modifications from the repo for the other registers or dialects.

If by "cloning this file" you mean "copy `es-ES-informal/core.yml` to `es-ES-formal/core.yml`", then it won't be easy. It will be easy when you do this first time, but if you do this again to sync with new translations, all previous adjustments in `es-ES-formal/core.yml` will be lost. This is the place where git could come handy, because if `es-ES-formal` would be fork of `es-ES-informal`, then git will be able to fetch new changes from `es-ES-informal` without overwriting previous adjustment for "formal" dialect.

Anyway, I suggest to start with single "Spanish", and after having this set up decide whether you want to add formal/informal dialects to Weblate. I could add language and import existing translations to Weblate tomorrow, but you must decide which dialect you want to import (AFAIK Internet communication is mostly informal, so I would use it as a base, but it is not my decision :P) and follow steps described at https://github.com/rob006-software/flarum-translations/wiki/How-to-start. Also I guess that you want to merge https://github.com/FlarumES/lang-spanish/pull/2 first.

**Comment by IamDarkle** [comment]
This is my Weblate [account](https://weblate.rob006.net/user/Darkle/) and I have already sent the invitation to robbot006, we are going to use `es-ES-informal` as a base. By the way is it possible to add another account with package maintainer permissions for @jslirola? Thank you!

**Comment by rob006** [comment]
> By the way is it possible to add another account with package maintainer permissions for @jslirola?

Yes, but I need to know his Weblate username.

**Comment by rob006** [comment]
OK, Spanish is already available on Weblate and translations for all supported extensions should be already imported: https://weblate.rob006.net/languages/es/flarum/

You probably should remove duplicated files with `.yaml` extension (bot exports translations to `.yml` files and I'm not sure how Flarum will behave if it finds two files with the same ID): https://github.com/FlarumES/lang-spanish/tree/main/locale/es-ES-informal

**Comment by jslirola** [comment]
> > By the way is it possible to add another account with package maintainer permissions for @jslirola?
> 
> Yes, but I need to know his Weblate username.

Hi, this is my profile: https://weblate.rob006.net/user/jslirola/

**Comment by rob006** [comment]
@jslirola Done.

**Comment by rob006** [comment]
I'm closing this for now. If you decide to add formal dialect to Weblate, please open new issue. Same for Mexican or Argentinian. It should be no problem to add these dialects to Weblate, you just need to decide which approach will be the most convenient for you.
