### ISSUE TITLE
Flarum translation into Hebrew

### ISSUE THREAD

**Issue by vgrakv** [rob006-software/flarum-translations#497]
Can you open a project for me in Hebrew, please? I want to start ...

**Comment by rob006** [comment]
Discussion was continued here: https://discuss.flarum.org/d/26633-translation-of-the-platform

I'm closing this for now since OP is no longer interested (or does not know how to create language pack). But if anyone would want to maintain Hebrew language pack, pleas add comment here and I open this issue.

As a reminder, here are instruction how to start: https://github.com/rob006-software/flarum-translations/wiki/How-to-start
