### ISSUE TITLE
Translation permission issues

### ISSUE THREAD

**Issue by Littlegolden** [rob006-software/flarum-translations#551]
Why Weblate user [@scvoet](https://weblate.rob006.net/user/scvoet/)'s translation can be applied to GitHub without my approval? I checked the log, it says "New Translation" instead of "New Suggestion"...

![image](https://user-images.githubusercontent.com/35162802/120062630-c7391880-c095-11eb-9c91-abe13e248371.png)

**Comment by Littlegolden** [comment]
Isn't it true that regular accounts can only make suggestions?

**Comment by rob006** [comment]
Regular accounts can directly translate and these translations will be pushed to master branch, but they can't mark translation as verified. The idea is that master branch may contain unverified translations from community, but before release you check all unverified translations and fix any potential mistakes, so stable release will always contain translations approved by maintainer.

**Comment by Littlegolden** [comment]
Thank you, I get it. But is it possible to disable users from directly translating blank strings? I am currently experiencing these issues:

1. In the past, I could click on "Strings" sorting to quickly see the untranslated extensions. Then I could translate them one by one in order. However, if other user translated these blank strings, the progress bar of the extensions turns green, and there is no sorting option to quickly filter out them.
![image](https://user-images.githubusercontent.com/35162802/120066473-2b190c80-c0a9-11eb-9867-33cc96e8cf7b.png)

2. The administrator cannot clearly know whether the translation was translated by someone else or not unless check the history log, however, each string can output a record, and translating an extension may generate a dozen pages of logs, which is not easy to find.

3. Some paid extensions I simply do not translate them intentionally, because if I cannot try it out, some translations may goes inaccurate. However, if other user translated one of the extensions, we caught in a dilemma… the translation will submit to master branch, and if I need to release the language pack, the unchecked translation will also be released. At this point it is not convenient either to delete the translation or to check the translation.

**Comment by rob006** [comment]
You can setup notifications about new or changed translations: https://weblate.rob006.net/accounts/profile/#notifications. Personally I'm also watching new commits in my language pack using RSS - it is easy to miss some unexpected changes if everything is automated.
For unverified translations probably the best way of finding them is using "waiting for review" filter: https://weblate.rob006.net/languages/zh_Hans/flarum/search/?q=&type=unapproved&ignored=False&checksum=&offset=
Also note that this sorting is not reliable, since it sorts records on single page - if untranslated extension is on second page, it won't appear when you sort on first page. I'd rather recommend using status page linked on https://rob006-software.github.io/flarum-translations/ to find extensions needing action.

For 3-rd point unfortunately I don't have a good solution. If you don't want premium extensions in your language pack, I can add them to list of ignored extensions [here](https://github.com/rob006-software/flarum-translations/blob/master/config/subsplits.php) - they still be available in Weblate, but translations will not be exported to your language pack.

**Comment by rob006** [comment]
Just to be clear, I had plans to add some kind of configuration that would allow language pack maintainers to blacklist/whitelist extensions for exporting from Weblate to language pack repository, so as language pack maintainer you could control this by editing config file directly in your repository. But now I just feel it does not make much sense. Language packs are moving to @flarum-lang, which main goal is to encourage community to contribute and focus on creating one complete language pack for each language. Adding special features that would allow maintainers to completely dismiss contributions from community seems off in that context. If you're not able verify translations for premium extensions, then just don't - let community to verify it and report bugs or propose fixes. It is still better than blocking translation of premium extensions.

**Comment by Littlegolden** [comment]
I quite agree with you~
