### ISSUE TITLE
Update Weblate to the latest version

### ISSUE THREAD

**Issue by qiaeru** [rob006-software/flarum-translations#626]
Currently, the version used on https://weblate.rob006.net/ is Weblate 3.9.1, released on October 28, 2019. As I write this issue, the latest version of the software is Weblate 4.7.1, released on June 30, 2021.

Is there any particular reason to use such an old version and not take advantage of the latest version in terms of security and features? 😉

Thanks!

**Comment by rob006** [comment]
This is related to dependencies - I have other stuff on this server and I need to upgrade all at once, which is not that easy (or even possible). Although I have plants to upgrade Weblate to latest version this summer, and since then it should be easier to keep it up to date.

**Comment by qiaeru** [comment]
Okay, nice. Dependencies are indeed annoying, that's why I use Docker. 😄 

But thanks for taking care of the update this summer!

**Comment by rob006** [comment]
I updated Weblate to the latest version.

**Comment by Littlegolden** [comment]
> I updated Weblate to the latest version.

Got a new issue: impossible to search CJK keywords.... 🤧

**Comment by rob006** [comment]
@Littlegolden Damn. :/ New Weblate switched to FULLTEXT search from MySQL, so it may work differently than before. Any hints how to improve this? I'm not even sure what is the problem.

**Comment by Littlegolden** [comment]
> @Littlegolden Damn. :/ New Weblate switched to FULLTEXT search from MySQL, so it may work differently than before. Any hints how to improve this? I'm not even sure what is the problem.

hope this is helpful: [ngram Full-Text Parser](https://dev.mysql.com/doc/refman/8.0/en/fulltext-search-ngram.html)

**Comment by rob006** [comment]
This needs be done in index definition in Weblate migrations. I'll take a look at this closer this weekend, but I would prefer to not mess up with Weblate source code. Unfortunately Weblate seems to be focused on PostgreSQL and ignores some issues with MySQL. :/

**Comment by rob006** [comment]
@Littlegolden I don't have good news for you. While using ngram improved search for Chinese, it also make it completely useless for other languages (or at least for Polish), since it returned a lot of unrelated results. With ngram_token_size=2 searching for "post" returned anything with "po" or "os" or "st", so you get a lot of results not even close to "post". I reverted this change as it brings more harm than good.

I would assume that migration to PostgreSQL would improve this, but I'm reluctant to installing another DBMS on this server (I need MySQL for other things). I need to think more about this, maybe this is a good reason to finally move Weblate to Flarum infrastructure. 

For now you can use a workaround: [regular expressions search](https://docs.weblate.org/en/weblate-4.8/user/search.html#regular-expressions). While regular expression is now what we need, syntax works reasonably well with raw strings and it does not use fulltext, so we can avoid its limitations. For simple search you can use it as `r"语言"` - searched phrase needs to be in the same form as in searched string. For more advanced searches you can combine multiple queries, for example `target:r"如果" target:r"概括整"` - in this way you can search for multiple words without worrying about order or phrases between them. It may not be convenient, but it should do the job until I decide about PostgreSQL migration.

![1cb0b110](https://user-images.githubusercontent.com/5972388/135729328-461302ee-f02c-47a9-9f8d-ccda53957226.png)

**Comment by Littlegolden** [comment]
> @Littlegolden I don't have good news for you. While using ngram improved search for Chinese, it also make it completely useless for other languages (or at least for Polish), since it returned a lot of unrelated results. With ngram_token_size=2 searching for "post" returned anything with "po" or "os" or "st", so you get a lot of results not even close to "post". I reverted this change as it brings more harm than good.
> 
> I would assume that migration to PostgreSQL would improve this, but I'm reluctant to installing another DBMS on this server (I need MySQL for other things). I need to think more about this, maybe this is a good reason to finally move Weblate to Flarum infrastructure.
> 
> For now you can use a workaround: [regular expressions search](https://docs.weblate.org/en/weblate-4.8/user/search.html#regular-expressions). While regular expression is now what we need, syntax works reasonably well with raw strings and it does not use fulltext, so we can avoid its limitations. For simple search you can use it as `r"语言"` - searched phrase needs to be in the same form as in searched string. For more advanced searches you can combine multiple queries, for example `target:r"如果" target:r"概括整"` - in this way you can search for multiple words without worrying about order or phrases between them. It may not be convenient, but it should do the job until I decide about PostgreSQL migration.
> 
> ![1cb0b110](https://user-images.githubusercontent.com/5972388/135729328-461302ee-f02c-47a9-9f8d-ccda53957226.png)

gotcha, regex is fine~

**Comment by rob006** [comment]
I created separate issue for search problems: https://github.com/rob006-software/flarum-translations/issues/765

Closing this one, since original issue was solved and Weblate is up to date.
