### ISSUE TITLE
Add Slovak language

### ISSUE THREAD

**Issue by CWKevo** [rob006-software/flarum-translations#627]
Based on Discord conversation, I kindly request Slovak language to be added.

Info:
- **Weblate username:** `Kevo`
- **GitHub Language repository:** https://github.com/flarum-lang/slovak

Thank you

**Comment by rob006** [comment]
Done: https://weblate.rob006.net/languages/sk/flarum/. You should also have maintainer permissions on Weblate.
Detailed translation status page should be generated at night, so you can check https://rob006-software.github.io/flarum-translations/status/sk.html tomorrow. 

I'm closing this issue, since it seems there is nothing more to do here. But if you have any questions, feel free to ask here or on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate).
