### ISSUE TITLE
Add support for Arabic language

### ISSUE THREAD

**Issue by neerugupta** [rob006-software/flarum-translations#630]
Please add Arabic language to the list of supported languages.

Language pack repository: https://github.com/neerugupta/flarum-lang-arabic
Language name: Arabic
Weblate username: neeru.gupta

**Comment by rob006** [comment]
Arabic language is available on Weblate since now: https://weblate.rob006.net/languages/ar/flarum/. You should also have maintainer permissions on Weblate.
Detailed translation status page should be generated at night, so you can check https://rob006-software.github.io/flarum-translations/status/ar.html tomorrow. 

I'm closing this issue, since it seems there is nothing more to do here. But if you have any questions, feel free to ask here or on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate).
