### ISSUE TITLE
Add finnish translation

### ISSUE THREAD

**Issue by MarkoKaartinen** [rob006-software/flarum-translations#700]
Starting a finnish translation: https://github.com/MarkoKaartinen/flarum-lang-finnish
Weblate user markok

Adder permissions to repo for you also.

Thanks.

**Comment by rob006** [comment]
I can add language to Weblate in 2-3 hours.

Have you considered hosting it under @flarum-lang? See https://discuss.flarum.org/d/27519-the-flarum-language-project for more info.

**Comment by MarkoKaartinen** [comment]
I did not know that existed. Thank you.
I will look into it tomorrow and get back to you! Thanks!

**Comment by rob006** [comment]
I have added Finnish language to Weblate: https://weblate.rob006.net/languages/fi/flarum/ . You should also have maintainer permissions, so you can translate on Weblate since now.
Although I did not configured exporting translations to language pack repository, since repository URL may change if you decide to move language pack under @flarum-lang org - I will setup this when you let me know about your decision.  If you decide to move your repository, you can transfer it to my account, I will move it further (you can't transfer repository directly to @flarum-lang org).

**Comment by MarkoKaartinen** [comment]
If you can move it under flarum-lang it would be great.

**Comment by rob006** [comment]
@MarkoKaartinen You need to go to https://github.com/MarkoKaartinen/flarum-lang-finnish/settings and transfer your repository to my account.

![c90394f4](https://user-images.githubusercontent.com/5972388/130782228-27da9569-d40e-4f03-881e-f77d8d6571e9.png)

**Comment by MarkoKaartinen** [comment]
Done!

**Comment by rob006** [comment]
Repo is transferred and bot is configured - it should export translations from Weblate in few minutes.
Soon someone from @flarum-lang team would create package on Packagist.

I'm closing this issue, since it seems there is nothing more to do here. But if you have any questions, feel free to ask here or on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate). Also, take a look at [wiki](https://github.com/rob006-software/flarum-translations/wiki/Features), you may find some useful information there.
