### ISSUE TITLE
Add `afrux/flarum-theme-base`

### ISSUE THREAD

**Issue by Littlegolden** [rob006-software/flarum-translations#727]
## [afrux/flarum-theme-base at Packagist](https://packagist.org/packages/afrux/flarum-theme-base)

 [![License](https://img.shields.io/github/license/afrux/flarum-theme-base)](https://github.com/afrux/flarum-theme-base/blob/master/LICENSE)

[![Latest Stable Version](https://img.shields.io/packagist/v/afrux/flarum-theme-base.svg?label=%22stable%22)](https://packagist.org/packages/afrux/flarum-theme-base) [![Total Downloads](https://img.shields.io/packagist/dt/afrux/flarum-theme-base)](https://packagist.org/packages/afrux/flarum-theme-base/stats)

https://github.com/afrux/asirem/issues/5 is using on `afrux/asirem` which is not translated.

**Comment by rob006** [comment]
I added this as `afrux/asirem`, since currently this is the only reliable way of including this in language pack. Still, this is far from perfect and bot won't automatically update links to translation on new release. I hope that https://github.com/flarum/core/issues/3091 will allow to handle these scenarios in less hacky way.
