### ISSUE TITLE
Korean Language Pack

### ISSUE THREAD

**Issue by hahagu** [rob006-software/flarum-translations#828]
Link to repository:
[hahagu/flarum-l10n-ext-korean](https://github.com/hahagu/flarum-l10n-ext-korean)

Weblate Username:
hahagu

**Comment by hahagu** [comment]
Ah okay, will just do that now.

**Comment by rob006** [comment]
It is better to move repository before integrating with Weblate, because it saves me some work with config update. If you want to move, you may transfer your repo to my account, I'll handle the rest. You can do this on https://github.com/hahagu/flarum-l10n-ext-korean/settings

After moving repo to flarum-lang, you can continue translation, migration to flarum-lang will not automatically mark it as finished, you need to tag release for that.

**Comment by rob006** [comment]
New repo: https://github.com/flarum-lang/korean
Weblate: https://weblate.rob006.net/languages/ko/flarum/

You have maintainer permissions on Weblate, so you should be able to mark translations as verified.

I'll ping someone to create new package on Packagist under `flarum-lang` vendor. In the meantime you can delete https://packagist.org/packages/hahagu/flarum-l10n-ext-korean package, since it will duplicate official `flarum-lang` package.

**Comment by hahagu** [comment]
Will do :)

**Comment by justoverclockl** [comment]
@hahagu package now is on packagist!
